import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Serif } from "next/font/google";
import { cn } from "~/lib/utils";
import { Toaster } from "~/shadcn/ui/sonner";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
});

const notoSerif = Noto_Serif({
  variable: "--font-noto-serif",
});

export const metadata: Metadata = {
  title: "Taskly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          geistMono.variable,
          geistSans.variable,
          notoSerif.variable
        )}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
